### ISSUE TITLE
VS Code R discovery

### ISSUE THREAD

**Issue by roaldarbol** [roaldarbol/r-template#4]
So an annoying issue is discovering Pixi R interpreters in VS Code. I don't know if there's a current solution - the R extension expects a single installation, there's `rig`, but no good solutions for project-wise installations at present.
I've also got an issue following this for Positron: https://github.com/posit-dev/positron/issues/3724

**Comment by roaldarbol** [comment]
Maybe some useful info here: 
- https://github.com/REditorSupport/vscode-R/issues/1487
- https://github.com/REditorSupport/vscode-R/wiki/R-Session-watcher#advanced-usage-for-self-managed-r-sessions
- https://github.com/REditorSupport/vscode-R/issues/1405

So R paths can possibly be specified inside a `settings.json` file, which then serve as `Workspace Settings`.

**Comment by roaldarbol** [comment]
@robinlovelace-ate This is somewhat resolved now! I've added a workspace settings file that automatically uses the R installation of the current project. I don't have a Linux station nearby (and it's been a while); how would you normally open VS Code from the command line on Linux? I've added a task to open it for MacOS (see the `pixi.toml`file), so can easily make a task for Linux too. :-)

On Mac, now you can use the template and simply run `pixi run code` and VS Code opens - it's got radian, httpgd and languageserver, so the setup should work well now! 

Just a note - there's no API for managing extensions yet (I'll add a link to the relevant vscode issue later), so you'll need to install extensions manually (e.g. Quarto).

I'll also change later to ask about which setup people will use (RStudio, VS Code, Jupyter). Or at least whether or not to install Jupyter as it's quite big.

Let me know if it works!

**Comment by roaldarbol** [comment]
The discovery doesn't work for VS Codium - need to figure out what that's about.

**Comment by robinlovelace-ate** [comment]
>  how would you normally open VS Code from the command line on Linux?

```sh
code path/to/project
```

Or via GitHub codespaces.

**Comment by robinlovelace-ate** [comment]
> The discovery doesn't work for VS Codium - need to figure out what that's about.

No issue for now as I'm mostly using VS Code.

**Comment by robinlovelace-ate** [comment]
> On Mac, now you can use the template and simply run pixi run code and VS Code opens - it's got radian, httpgd and languageserver, so the setup should work well now!

Bingo, that sounds really good, and kind of wondering why I didn't think of that!

**Comment by robinlovelace-ate** [comment]
> Just a note - there's no API for managing extensions yet (I'll add a link to the relevant vscode issue later), so you'll need to install extensions manually (e.g. Quarto).

That can be handled by the devcontainer.json file when using the wonderful devcontainer setup for Dockerised VS Code.

**Comment by roaldarbol** [comment]
I think this is now resolved - for opening in a Docker container, if you can provide me with a minimal `devcontainer.json` and let me know if it needs to go in a specific folder I can add that too. :-)

**Comment by robinlovelace-ate** [comment]
OK awesome, thanks @roaldarbol, will cc in my main account also @robinlovelace.
